### ISSUE TITLE
Add more method to IRepository

### ISSUE THREAD

**Issue by KINGGUOKUN** [WeihanLi/WeihanLi.Common#100]
Add the following methods to IRepository interface:
int Update(TEntity entity, params Expression<Func<TEntity, object>>[] propertyExpressions);
int Update(TEntity entity, params string[] propertyNames);
Task<int> UpdateAsync(TEntity entity, Expression<Func<TEntity, object>>[] propertyExpressions, CancellationToken cancellationToken = default);
Task<int> UpdateAsync(TEntity entity, string[] propertyNames, CancellationToken cancellationToken = default);

Purpose:
Make application service layer depend the IRepository instead of the IEFRepository layer so it decouples the domain service and the infrusture.

**Comment by WeihanLi** [comment]
we should know that which is the primary key to specific the where condition,
we could treat the property with `KeyAttribute`  or `Id`  property as primary key for now,  but maybe another great way to config these mappings

**Comment by WeihanLi** [comment]
what about `Delete(TEntity entity)`?

**Comment by WeihanLi** [comment]
new package released(preview) [WeihanLi.EntityFramework 1.9.1-preview-20200805-131255](https://www.nuget.org/packages/WeihanLi.EntityFramework/1.9.1-preview-20200805-131255)

**Comment by KINGGUOKUN** [comment]
> what about `Delete(TEntity entity)`?

Yes,  Delete(TEntity entity) and KeyAttribute or Id property is enough.
