### ISSUE TITLE
DecompressGZip error

### ISSUE THREAD

**Issue by gitlsl** [WeihanLi/WeihanLi.Common#155]
https://github.com/WeihanLi/WeihanLi.Common/blob/2bd5a5651299e2e97be1bc275f0a335539a001cd/src/WeihanLi.Common/Extensions/CompressionExtension.cs#L90

这里应该用  outStream.ToArray   not  outStream.GetBuffer

**Comment by WeihanLi** [comment]
Thanks

**Comment by WeihanLi** [comment]
发布了一个新版本 1.0.59，感谢感谢
https://www.nuget.org/packages/WeihanLi.Common/1.0.59
