### ISSUE TITLE
防SQL注入正则表达式的问题

### ISSUE THREAD

**Issue by kissxic** [WeihanLi/WeihanLi.Common#6]
数据库MSSQL Server，
使用的查询语句：select ArmId as Id,ArmName as Name from arm
位置：
WeihanLi.Common/Helpers/SecurityHelper.cs
 
使用两种表达式验证
IsSafeSqlString 方法都是返回false，
该方法不能用于执行sql语句前判断注入吗?

**Comment by WeihanLi** [comment]
不再维护了，下个版本将删掉这个正则，sql注入的根本原因在于字符串的拼接，只需要不进行字符串拼接，使用参数化查询就不会有问题，如果实在需要拼接sql，把拼接的字符串中的单引号去掉就可以了，一般的做法是把单引号替换为两个单引号 `Replace("'", "''")`
